### ISSUE TITLE
LIGHT THEME: Suppress left nav entirely?

### ISSUE THREAD

**Issue by KathJohnson** [meetinghouse/cms#243]
@jboz62 I think you mentioned you expected this to maybe come up, but here's a note I got in response to the client for 
heirloomwindows and weatherstrippingkit

"The one thing that REALLY concerns me is the inefficient use of space. I think I've mentioned this to John. On both sites, the first thing that jumps out at me is that 25% of my prime real estate is dedicate to redundant information. The same links are on the left side bar as are just above in the menu bar. This shifts all the copy to the right and gives it an unsettling, unbalanced feeling. If we have to have the social media links, put them in the header or footer, but don't take up valuable copy space."

So, three questions, which you can answer in terms of estimated hours, if you do find them feasible:

1. How feasible is it to suppress the left nav AND the social media links on one site as a custom thing?
2. Can the social media links be moved somewhere else, like to the footer?
3. How feasible is it to make suppression of the left nav and social media links toggle-able?

**Comment by jboz62** [comment]
@KathJohnson @1sp I think those questions can better be answered by Sudhir. I can, however, offer some advice.

1) On the social icons, those are housed inside the sidebar menu code. Maybe there should be a toggle for displaying them in either the header or footer? I could place them in the footer or header using CSS on his sites, if needed.

2) On the sidebar menu for light theme, I've never liked the sidebar and think it should go away entirely, but that's not up to me. It is redundant and takes up valuable real estate, like he said. One fix might be to get rid of the sidebar and change the Bootstrap class to col-md-12 (I think it is, off the top of my head) for full-width in the content area and move the social as recommended in #1. Another way is to keep it and make it so you can disable it in the admin settings then conditionally add the bootstrap class to make it full-with. I'm not sure which is more difficult, Sudhir can tell us how long it would take to do those two options.

I think this is also the issue with New England Soundproofing, the sidebar seems to bother him as well, although he hasn't articulated it as well as the heirloom windows client.

**Comment by 1sp** [comment]
1) As John rightly said, the social icons could go either in header or footer. The exact placement in the section could be discussed. From a user's perspective, I would prefer having a admin setting to control the placement of social icons

2) This again could get a place in settings page as "Enable sidebar". If disabled the content area will take 100% container width

**Comment by jboz62** [comment]
Ok, thanks, Sudhir. Any idea of the timeframe on those two options? Since we already have the sidebar on several sites, we probably have to keep it, so making it optional in the settings is probably best. Please advise as to the number of hours for these so we can budget for it. Thanks you.

**Comment by 1sp** [comment]
For the (1) I would need to know the placement of the the social media icon section. If it is not something tricky , I can wrap both 1. and 2 within couple of hours time

**Comment by meetinghouse** [comment]
@sp1 I'd say that if the left nav is suppressed that social media icon bar
should go to the footer. It should default to centered. @jboz62 Would that
be easily editable in HTML, then, in case we need to left-justify it or
something? I'm just trying to foresee likely issues with that.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by jboz62** [comment]
That sounds like a good plan to me. Moving the social icons around, centered, left or right is easy with CSS once they are placed with the footer, not a problem. Default to centered and I can move them left or right if needed for a particular design.

**Comment by jboz62** [comment]
@KathJohnson Are we a go on this, Katherine? Let Sudhir know if he should work on this please. Thank you.

**Comment by KathJohnson** [comment]
I just spoke with John Corbett about this, and yes, this is a go. Please proceed, Sudhir. Thanks.

**Comment by 1sp** [comment]
The functionality is working. Tested on the light theme.

1. Admin setting
![enable_left_nav_setting](https://cloud.githubusercontent.com/assets/60359/15019817/308bc90c-123d-11e6-999e-2aca04f31db7.png)

2. Left nav disabled
![without_left_nav](https://cloud.githubusercontent.com/assets/60359/15019845/497d0e08-123d-11e6-9260-f48ebf5a3536.png)

3. Left nav enabled
![with_left_nav](https://cloud.githubusercontent.com/assets/60359/15019859/55b66f0c-123d-11e6-8ebf-b200aad95f9a.png)

**Comment by jboz62** [comment]
That looks great, Sudhir, thank you. Is that on a branch we can test?

**Comment by 1sp** [comment]
Yes, it is on the same i221 branch.

I have implemented and tested it on pages for light theme (wasn't sure about the dark theme).

**Comment by KathJohnson** [comment]
That is good news, and the screenshots look good. I deployed the code from branch i221 to the test site menus.corbettresearchgroup.com. but I don't see the new checkbox on the Admin Settings page.

**Comment by jboz62** [comment]
I’m not seeing it either, and the home page item is missing.

**Comment by 1sp** [comment]
This is how it would look like, are all the migrations in place ? 

![chrome_2016-05-05_00-07-25](https://cloud.githubusercontent.com/assets/60359/15025174/a4375610-1255-11e6-814e-470eed04e6b7.png)

**Comment by 1sp** [comment]
please share admin login of http://menus.corbettresearchgroup.com

**Comment by jboz62** [comment]
I thought I sent you the admin login, they are all the same login. Let me know if you have that. Thanks.

**Comment by 1sp** [comment]
I believe the latest changes are not on the site. Please confirm is changes till commit#/fdd94c39c0140b2e402f8377606acca5bfa5148c (https://github.com/1sp/cms/commit/fdd94c39c0140b2e402f8377606acca5bfa5148c)are deployed

**Comment by 1sp** [comment]
There are a couple of migrations , don't miss them :)

**Comment by jboz62** [comment]
Sudhir, any idea why the migrations don’t run if there’s a “php artisan migrate” in the script? It should run them, shouldn’t it?

**Comment by 1sp** [comment]
Actually it is not about the migration, even the changes to the templates (e.g the new checkbox setting) were missing. So I am guessing that my commit wasn't pulled.

**Comment by jboz62** [comment]
It doesn’t look like anything was migrated:

Wed May  4 14:26:46 EDT 2016
Already on 'i221'
Your branch is up-to-date with 'origin/i221'.
From github.com:meetinghouse/cms
 * branch            i221       -> FETCH_HEAD
Already up-to-date.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
> php artisan cms:setup
Nothing to migrate.

**Comment by jboz62** [comment]
Hmm, it has a git pull origin $BRANCH and $BRANCH is set to i221.

**Comment by 1sp** [comment]
Ah, I think you are pulling from the meetinghouse's repo not mine. I have made a pull request so the the commit lies on my repository.

You can add a new remote to your copy, say 'sudhir ' and point it to my fork and then do a `git pull sudhir i221`

**Comment by jboz62** [comment]
Do you mean the previous pull request you made? I don't see any current pull requests. 

I'll try the remote branch you mentioned, thank you.

**Comment by 1sp** [comment]
Please ignore my previous message.I just merged 1sp/i221 into meetinghouse/i221. Just do a regular pull again and you will see my changes

**Comment by jboz62** [comment]
This setup looks great, Sudhir, thank you for the work on that! 

I ran into an error while trying to create a page, also get the same error when trying to edit an existing page. Please see screenshot.
![screen shot 2016-05-04 at 6 01 31 pm](https://cloud.githubusercontent.com/assets/11739120/15030855/c1a507b6-1222-11e6-9452-76ab1246213e.png)

**Comment by jboz62** [comment]
Another issue I'm seeing is that we lost our "active"/"not-active" classes on the top and sidebar menu. The reason for that is that `Request::server('PATH_INFO')` doesn't seem to work. We figured out that `$_SERVER['REQUEST_URI']` does work, so we changed most of them, you may have seen it in the sidebar.dark file and top-nav file. Can you get those working again? Looks like it's missing from the light theme sidebar, please add it in there as well. I'll need those classes for styling the menus. 

You can see it working on http://lightthemetest.corbettresearchgroup.com/ on the top nav, should also be working on the sidebar nav. You can also see it on the sidebar nav for http://shconstruction2.corbettresearchgroup.com/about (dark theme)

I'm going to need this functionality for this site on the top nav and sidebar nav, but it needs to be available for all sites: http://newenglandsoundproofing.corbettresearchgroup.com/

This is the contact page, you can see it says "not-active" when it is the active page.

![screen shot 2016-05-04 at 6 34 47 pm](https://cloud.githubusercontent.com/assets/11739120/15031676/7b5bf0ca-1228-11e6-937f-3204a2d15db5.png)



This is from a working site where the active page has the "active" class:

![screen shot 2016-05-04 at 6 41 50 pm](https://cloud.githubusercontent.com/assets/11739120/15031697/9d3c24e4-1228-11e6-8474-c6d267cbc210.png)

Thank you.

**Comment by jboz62** [comment]
@1sp Ok, one last thing, I hope ;)

When you disable the left menu and update the settings, the menu remains visible until you logout of the admin or browse away by clicking on a menu item. This might be confusing to some users. Can we add to the message under the checkbox that says "Use this to enable or disable left navigation." something like "If you disable the left sidebar menu, it will remain visible while in the admin. To view the full-width page or post, please click on a menu item". Either that, or we should just make in not display after update in the admin. @KathJohnson What do you think about that, Katherine?

**Comment by jboz62** [comment]
@1sp Sudhir, maybe this will be the last one :) 

Noticed one more problem while I while fixing another issue. The left menu on the dark theme can be disabled. This should only work for the light theme, not on the dark theme as it only has one menu. Can you separate the functionality so that the disable checkbox only works on the light theme? Thank you.

**Comment by jboz62** [comment]
@1sp Guess there are still some bugs to work out. One more thing... On the dark theme menu, when you click on "home" or "contact" (single pages with no sub-items) they are repeated in the sub-nav area below. Those should not be there, see screenshots. Thank you.

![screen shot 2016-05-04 at 9 58 46 pm](https://cloud.githubusercontent.com/assets/11739120/15034453/e44ff8c2-1243-11e6-872b-3bf3e7b56929.png)
![screen shot 2016-05-04 at 9 59 13 pm](https://cloud.githubusercontent.com/assets/11739120/15034457/ea783854-1243-11e6-81ca-67c23cb10f35.png)

**Comment by KathJohnson** [comment]
It's probably easier to show the menu in the admin pages and just put some verbiage in there to explain that it won't show on the live pages. So I'd do that.

I'm able to suppress the menu on the menus.corbettresearchgroup.com site now, but I don't see the social icon bar anywhere when it's suppressed. Should it be in the footer?

**Comment by jboz62** [comment]
Shows up for me, maybe clear your cache? All the way at the bottom:

![screen shot 2016-05-05 at 2 39 03 pm](https://cloud.githubusercontent.com/assets/11739120/15053196/62e8f36a-12cf-11e6-9ff3-96af1a9788b7.png)

**Comment by jboz62** [comment]
@KathJohnson Looks like Sudhir is busy on some other jobs on Upwork, probably why he hasn't responded today. We need him to fix the bugs so we can push this out to some of the sites soon. We need it on the Heirloom and WindowLogic site and also the New England Soundproofing site so I can do the changes for the mockup.

**Comment by jboz62** [comment]
@1sp Sudhir, when you get these bugs worked out, can you do a final pull request so we can merge this into into "blog". Please push this through as soon as you're able. Thank you.

**Comment by 1sp** [comment]
Sorry @jboz62 , @KathJohnson , seems like my last commit disrupted a lot of things. I will be more careful from now on :)

I am pushing a commit with fixes as soon as possible.

**Comment by KathJohnson** [comment]
Many, many thanks to both of your for your attention to detail on this. I
do agree, John, that it needs to go live soon, and that is the client site
list I am working form as well. Of course, the remaining issues are a
priority.

**Comment by 1sp** [comment]
I just merged changes in https://github.com/meetinghouse/cms/tree/1sp-in . Please review

**Comment by jboz62** [comment]
Ah, never mind my last email, I see. Once this is reviewed it will be merged into “blog”? I’ll take a look at it later today.

**Comment by jboz62** [comment]
Sudhir, the changes look good, but still seeing some things that were missed in my previous comments. The "active" and "not-active" classes are still not working. Please see above comments for the fix on that. In this screenshot, the Contact page is active, but the class says "not-active".

![screen shot 2016-05-06 at 2 13 18 pm](https://cloud.githubusercontent.com/assets/11739120/15082329/28c68f0a-1395-11e6-8d47-0d539479bfa7.png)

This is also not working on the dark theme, which will break the shconstuction.com site if we push the code to it, so this needs to be fixed before we merge to "blog".

I can add these changes if you don't have time, but I have too much going on already. If you can do it, please do. Thank you.

**Comment by jboz62** [comment]
The other thing I noticed is with the message on the sidebar menu, should be changed to notify users that sidebar will be visible in admin and not visible on front-end of site. This is not urgent, though, I can add this later. Thank you.

**Comment by jboz62** [comment]
Katherine, the bug fixes Sudhir did look good, just one more thing to fix with the menu classes “active” and "not-active”, they are not working still. I mentioned this to Sudhir and hopefully he can get it fixed soon. Once that’s working, this should be ready to merge to “blog” and pushed out to the sites we discussed. If he can get it done this weekend, I will have him merge it and then I can deploy to new england sound so I can get those changes done for Steve.

**Comment by 1sp** [comment]
I just pushed a fix for the above. The menus should look a lot better now :) 

On light them, the parent menu items in left navigation get active class in h4 tag
![chrome_2016-05-07_00-36-28](https://cloud.githubusercontent.com/assets/60359/15083615/d878a252-13eb-11e6-8b50-7b3926d7d8d5.png)


Please let me know if anything else need a fix

**Comment by meetinghouse** [comment]
I see the social icons now. I was looking for them in the editable footer
field on the Admin Settings page, but I suppose they would need to be
edited by you, John, not by the user. That's fine. I think the
functionality of suppressing the left nav is good at this point, though
we're still testing the other menu management pieces.

If it's possible to roll out *just *the left nav suppression piece to the
blog branch, then I think we probably can do that.

**Comment by jboz62** [comment]
Yes, that’s not an item that would be editable in the footer, it’s dynamically generated. I can move it around some using CSS, though, if needed. 

All changes have been merged to blog already. I’ve been working with it and haven’t seen any issues so far, except what you mentioned, but that could be a missing migration table.

**Comment by meetinghouse** [comment]
I was behind in my understanding of where we are on rolling this out. Do
you mind if I close this issue? I think it is working.

**Comment by jboz62** [comment]
Yes, sorry, I wanted to wait, but didn’t hear back from you, so we merged it. If needed it is possible to roll back changes to an earlier state. However, I do think it’s working pretty well, except for the bug you found. Let’s see what Sudhir comes back with.

I would try doing another deploy on lightthemetest to see if that frees it up, you may be missing the last migration table he added.

**Comment by meetinghouse** [comment]
Don't apologize. I am very happy to see how productive you've been.

By the way, if you prefer to hand Steve Drago back off to me, that would be
fine. Once you think the technical side of things is sort of ironed out, I
will work with him on the content.

Sincerely,
Katherine Johnson, Research Director
Corbett Research Group
http://www.restorationtrades.com
"Web Marketing that Works"

Publishers of:

The Custom Building & Restoration Trades Directory
http://www.restorationtradesdirectory.com

The Building Arts Notebook, "Journal of the Guild of Building Artisans"
http://buildingartisansguild.com/

Email:  katherine@restorationtrades.com
Phone: (413) 475-3154

**Comment by jboz62** [comment]
That’s fine, if you want to work with him on content, I think we’re pretty much there, but I’m sure there will be tweaks he wants. One he already wants is to change “portfolios” to “projects”, but I don’t think that’s possible without changing the code base. He also wanted to hide “all projects” in the menu, not sure why that’s showing up, maybe another thing for Sudhir to address. I put it at the end and hid it. We also hid the top menu. You can see the changes on the site.

I give you a ring soon.

**Comment by jboz62** [comment]
@1sp Sudhir, it looks like there's a bug remaining on this feature. When you click on one of the portfolio items on light theme, the sidebar menu reappears. See: http://heirloomwindows.corbettresearchgroup.com/exterior

Thank you.

**Comment by 1sp** [comment]
Sorry, the last fix was only done for the pages resources. I have now done the same change for posts, portfolios and projects resources. Changes have been merged in blog branch. Please review.

Thanks

**Comment by jboz62** [comment]
Thank you, Sudhir, I’ll check it out.

**Comment by KathJohnson** [comment]
Hello. Now that the deployment problem seems to be worked out, I deployed the new code to the two sites who were immediately requesting it (heirloomwindows and weatherstrippingkit) and the left nav is successfully suppressed on portfolio pages as well. The only thing stopping me from marking this as closed is that I haven't tested it for dark theme. Will do once menu management for dark theme has been sorted.

**Comment by jboz62** [comment]
Thanks, Katherine. I think menu management is basically sorted out, except, it seems there is custom coding on the S+H site that needs to be accounted for. Has Sudhir looked into that yet? We need to know what, if any, differences there are between what’s on the blog and what’s on S+H. Once we determine that, we can have him allow for the “builder’s notebook” type functionality to be in the base code. Not sure if I’m behind on this, but as far as I know, this hasn’t been determined yet.

**Comment by meetinghouse** [comment]
Excellent. Just so all are on the same page, I created Issue #267 to track
the developing menu management functionality in dark theme, so any other
comments/suggestions could probably go there.

**Comment by jboz62** [comment]
This item is completed, closing this issue.
